var sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),D=null,sec='dash',root=document.getElementById('root');
var SECS={dash:'Dashboard',home:'Home Page',portfolio:'Portfolio & Videos',about:'About & Skills',services:'Services',contact:'Contact & Social',images:'Images',theme:'Theme Colors',security:'Security'};
var BL={projects:{t:'New project',c:'Shorts',u:'',img:'',f:false,ap:false,mu:true,lp:false,ct:true,vert:false,st:''},'about.stats':{n:'0',l:'New stat'},'about.skills':{n:'New skill',p:'80'},'services.items':{t:'New service',d:'Describe this service.',p:''}};
function toast(m,bad){var t=document.getElementById('toast');t.textContent=m;t.className='show'+(bad?' bad':'');clearTimeout(toast.t);toast.t=setTimeout(function(){t.className=''},3500)}
function getp(p){return p.split('.').reduce(function(o,k){return o==null?o:o[k]},D)}
function setp(p,v){var k=p.split('.'),l=k.pop();k.reduce(function(o,x){return o[x]},D)[l]=v}
async function save(){D.about.skills.forEach(function(s){s.p=String(Math.max(0,Math.min(100,parseInt(s.p)||0)))});D.home.featured_count=String(Math.max(1,parseInt(D.home.featured_count)||3));
 var r=await sb.from('site').upsert({id:1,data:D});if(r.error)toast('Not saved: '+r.error.message,1);else toast('Saved. Your live website is updated.')}
function inp(l,p,t){var v=getp(p);return'<label>'+esc(l)+(t=='area'?'<textarea data-p="'+p+'" rows="4">'+esc(v)+'</textarea>':'<input type="'+(t||'text')+'" data-p="'+p+'" value="'+esc(v)+'">')+'</label>'}
function chk(l,p){return'<label class="ck"><input type="checkbox" data-p="'+p+'"'+(getp(p)?' checked':'')+'> '+esc(l)+'</label>'}
function img(l,p){var v=getp(p);return'<div><div class="th2">'+(v?'<img src="'+esc(v)+'" alt="">':'<span>No image</span>')+'</div><label>'+esc(l)+'<input type="file" accept="image/*" data-up="'+p+'"></label></div>'}
function list(path,label,fields,th){return(getp(path)||[]).map(function(r,i){var q=path+'.'+i+'.';return'<div class="row"><div class="rh"><b>'+label+' '+(i+1)+'</b><button class="del" data-del="'+path+'.'+i+'">Remove</button></div>'+(th?img('Thumbnail (optional: if empty, the YouTube thumbnail is used)',q+'img')+(ytId(r.u)?'<p class="sub">Video found &#10003;</p>':'<p class="sub">No valid YouTube link yet</p>'):'')+fields.map(function(f){return f[2]=='chk'?chk(f[1],q+f[0]):inp(f[1],q+f[0],f[2])}).join('')+'</div>'}).join('')+'<p><button class="btn ghost" data-add="'+path+'">+ Add '+label.toLowerCase()+'</button></p>'}
var SV='<p><button class="btn" data-save>Save changes</button></p>';
function view(){var o='';switch(sec){
case'dash':o='<p class="sub">Pick what you want to edit. Every save updates your live website immediately.</p><div class="dash">';var d={home:'Greeting, name, title, featured work',portfolio:D.projects.length+' projects. YouTube links, autoplay, mute, loop',about:'About text, numbers, skill bars',services:D.services.items.length+' services. Add or remove',contact:'Email, WhatsApp, social links',images:'Profile photo and About photo',theme:'Switch the whole site colors',security:'Change your password'};for(var k in d)o+='<button class="dc" data-sec="'+k+'"><b>'+SECS[k]+'</b><span>'+esc(d[k])+'</span></button>';o+='<a class="dc" href="index.html" target="_blank"><b>View live website</b><span>Opens in a new tab</span></a></div>';break;
case'home':[['brand','Logo / brand name'],['badge','Availability badge'],['hi','Greeting'],['name','Big headline'],['title','Job title'],['tagline','Short description','area'],['cta1','Main button text'],['featured_title','Featured work heading'],['featured_count','How many featured projects','number']].forEach(function(f){o+=inp(f[1],'home.'+f[0],f[2])});o+='<p class="sub">Featured projects are chosen in Portfolio & Videos. Profile photo is in Images.</p>'+SV;break;
case'portfolio':o=inp('Page heading','portfolio.title')+inp('Intro text','portfolio.intro','area')+'<h3>Projects & videos</h3><p class="sub">Paste a normal YouTube link (watch, youtu.be or Shorts). The video plays inside your site.</p>'+list('projects','Project',[['t','Title'],['c','Category (e.g. VSL, Shorts, Amazon PPC)'],['u','YouTube link'],['f','Show in Home featured work','chk'],['ap','Autoplay when it scrolls into view (always muted)','chk'],['mu','Start muted when clicked','chk'],['lp','Loop the video','chk'],['ct','Show player controls','chk'],['vert','Vertical 9:16 player (automatic for Shorts links)','chk'],['st','Start at (seconds, optional)','number']],true)+SV;break;
case'about':o=inp('Heading','about.title')+inp('Paragraph 1','about.p1','area')+inp('Paragraph 2','about.p2','area')+'<h3>Numbers</h3>'+list('about.stats','Stat',[['n','Number'],['l','Label']])+'<h3>Skills</h3>'+inp('Skills heading','about.skills_title')+list('about.skills','Skill',[['n','Skill name'],['p','Percent (0 to 100)','number']])+SV;break;
case'services':o=inp('Heading','services.title')+inp('Intro text','services.intro','area')+list('services.items','Service',[['t','Service name'],['d','Description','area'],['p','Price (optional)']])+SV;break;
case'contact':o=inp('Heading','contact.title')+inp('Intro text','contact.intro','area')+inp('Contact email','contact.email','email')+inp('WhatsApp number (with country code)','contact.whatsapp')+'<h3>Social links (full URLs, empty hides it)</h3>';Object.keys(D.contact.social).forEach(function(k){o+=inp(k.charAt(0).toUpperCase()+k.slice(1),'contact.social.'+k)});o+=SV;break;
case'images':o='<p class="sub">Images upload and go live straight away. Project thumbnails are in Portfolio & Videos.</p>'+img('Profile photo (Home page)','images.profile')+img('About page photo (uses profile photo if empty)','images.about');break;
case'theme':o='<p class="sub">Click a theme. It changes the whole website instantly.</p>';for(var t in THEMES){o+='<button class="tc'+(D.theme==t?' on':'')+'" data-theme="'+t+'"><b>'+THEMES[t][0]+'</b><span class="sw">'+THEMES[t][1].map(function(c){return'<i style="background:'+c+'"></i>'}).join('')+'</span></button>'}break;
case'security':o='<p class="sub">Change your login password. Use a long, unique one.</p><label>New password (8+ characters)<input type="password" id="np" autocomplete="new-password"></label><label>Repeat new password<input type="password" id="np2" autocomplete="new-password"></label><button class="btn" data-pw>Change password</button>';break}
return o}
function render(){root.innerHTML='<div class="lay"><aside><h2>Admin Panel</h2>'+Object.keys(SECS).map(function(k){return'<button class="nv'+(k==sec?' on':'')+'" data-sec="'+k+'">'+SECS[k]+'</button>'}).join('')+'<a class="nv" href="index.html" target="_blank">View website</a><button class="nv" data-out>Log out</button></aside><main><h1>'+SECS[sec]+'</h1>'+view()+'</main></div>'}
async function upload(f,p){if(f.size>5*1048576)return toast('Image is too large (max 5 MB)',1);var ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');var n=Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+ext;
 var r=await sb.storage.from('images').upload(n,f,{contentType:f.type});if(r.error)return toast('Upload failed: '+r.error.message,1);setp(p,sb.storage.from('images').getPublicUrl(n).data.publicUrl);await save();render()}
root.addEventListener('input',function(e){var t=e.target;if(t.dataset.p)setp(t.dataset.p,t.type=='checkbox'?t.checked:t.value)});
root.addEventListener('change',function(e){var t=e.target;if(t.dataset.up&&t.files[0])upload(t.files[0],t.dataset.up)});
root.addEventListener('click',async function(e){var t=e.target.closest('button');if(!t)return;var d=t.dataset;
 if(d.sec){sec=d.sec;render()}else if('save' in d){await save()}
 else if(d.add){getp(d.add).push(JSON.parse(JSON.stringify(BL[d.add])));await save();render()}
 else if(d.del){if(!confirm('Remove this item?'))return;var k=d.del.split('.'),i=+k.pop();getp(k.join('.')).splice(i,1);await save();render()}
 else if(d.theme){D.theme=d.theme;applyTheme(d.theme);await save();render()}
 else if('out' in d){await sb.auth.signOut();location.reload()}
 else if('pw' in d){var a=document.getElementById('np').value;if(a.length<8)return toast('Password must be at least 8 characters',1);if(a!==document.getElementById('np2').value)return toast('The two passwords do not match',1);var r=await sb.auth.updateUser({password:a});r.error?toast(r.error.message,1):toast('Password changed.')}});
function loginView(m){applyTheme('charcoal');root.innerHTML='<div class="login"><h1>Admin login</h1><p class="sub">Sign in to manage your website.</p>'+(m?'<div class="er">'+esc(m)+'</div>':'')+'<div class="row"><label>Email<input id="em" type="email" autocomplete="username"></label><label>Password<input id="pw" type="password" autocomplete="current-password"></label><button class="btn" id="go">Log in</button></div><p class="sub">First time? Use the test login from README.txt, then change the password in Security.</p></div>';
 var go=async function(){var r=await sb.auth.signInWithPassword({email:document.getElementById('em').value.trim(),password:document.getElementById('pw').value});r.error?loginView('Wrong email or password.'):start()};document.getElementById('go').onclick=go;document.getElementById('pw').onkeydown=function(e){if(e.key=='Enter')go()}}
async function start(){var r=await sb.from('site').select('data').eq('id',1).maybeSingle();D=(r.data&&r.data.data)||JSON.parse(JSON.stringify(DEFAULTS));applyTheme(D.theme);sec='dash';render()}
sb.auth.getSession().then(function(s){s.data.session?start():loginView()});
