var DEFAULTS={theme:'charcoal',
home:{brand:'Salman Ahmed',badge:'Available for new projects',hi:'Hey, there',name:'I am Salman Ahmed',title:'Short-form & Long-form YouTube Video Editor',tagline:'I edit videos that hold attention: fast shorts, story-driven YouTube videos, and sales videos that convert.',cta1:'See my work',featured_title:'Featured work',featured_count:'3'},
portfolio:{title:'Portfolio',intro:'VSLs, shorts and Amazon PPC product ads I have edited.'},
about:{title:'About me',p1:"I'm Salman Ahmed, a video editor who turns raw footage into videos people watch to the end. I edit YouTube videos of every length, from 30-second shorts to full-length episodes.",p2:'I also cut video sales letters (VSLs) and Amazon PPC product ads, where every second has to earn the click.',stats:[{n:'100+',l:'Videos edited'},{n:'3',l:'Formats: shorts, long-form, ads'},{n:'48h',l:'Typical turnaround'}],skills_title:'Skills',skills:[{n:'Adobe Premiere Pro',p:'95'},{n:'Short-form editing',p:'95'},{n:'Long-form YouTube editing',p:'92'},{n:'VSL editing',p:'90'},{n:'After Effects & motion graphics',p:'85'},{n:'Amazon PPC ads',p:'88'}]},
services:{title:'Services',intro:'What I can do for you.',items:[{t:'Short-form editing',d:'Vertical videos for YouTube Shorts, Reels and TikTok with captions and strong hooks.',p:''},{t:'Long-form YouTube editing',d:'Story-driven edits with pacing, sound design and graphics.',p:''},{t:'VSL editing',d:'Video sales letters built to hold attention and drive action.',p:''},{t:'Amazon PPC product ads',d:'Short product videos made to lift click-through and sales.',p:''}]},
contact:{title:"Let's work together",intro:"Tell me about your video and I'll reply with a plan and a quote.",email:'hello@example.com',whatsapp:'+920000000000',social:{instagram:'',youtube:'',facebook:'',linkedin:'',tiktok:'',x:''}},
images:{profile:'',about:''},
projects:[['VSL Project 01','VSL',1],['VSL Project 02','VSL',0],['Short 01','Shorts',1],['Short 02','Shorts',0],['Product Ad 01','Amazon PPC',1],['Product Ad 02','Amazon PPC',0]].map(function(a){return{t:a[0],c:a[1],u:'',img:'',f:!!a[2],ap:false,mu:true,lp:false,ct:true,vert:false,st:''}})};
var THEMES={charcoal:['Charcoal Orange',['#0d0b0a','#171210','#1c1613','#f6efe9','#a89a90','#2e2520','#ff6a00']],midnight:['Midnight Blue',['#070b16','#0e1424','#131b30','#eaf0ff','#93a1c4','#222c47','#3d8bff']],purple:['Slate Purple',['#0f0d14','#17141f','#1d1927','#f1edf8','#a79fb8','#2d283a','#a566ff']],emerald:['Emerald Dark',['#060d0b','#0c1613','#111e1a','#e9f6f1','#8fb0a5','#1f332c','#16c784']]};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function ytId(u){var m=String(u||'').match(/(?:youtu\.be\/|youtube(?:-nocookie)?\.com\/(?:watch\?(?:[^#]*&)?v=|shorts\/|embed\/|live\/|v\/))([\w-]{11})/);return m?m[1]:''}
function applyTheme(k){var t=(THEMES[k]||THEMES.charcoal)[1],r=document.documentElement;['bg','bg2','card','text','mute','line','o'].forEach(function(n,i){r.style.setProperty('--'+n,t[i])})}
async function loadData(){try{var r=await fetch(SUPABASE_URL+'/rest/v1/site?id=eq.1&select=data',{headers:{apikey:SUPABASE_KEY},cache:'no-store'});var j=await r.json();if(j&&j[0]&&j[0].data)return j[0].data}catch(e){}return JSON.parse(JSON.stringify(DEFAULTS))}
